stages:
  - build

build_job:
  stage: build
  tags: [ "macos", "maven" ]
  image: maven:3.9-jdk-21
  script:
    - mvn clean install
    - mvn clean verify -DdisplayName=true -B || true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
